src/PHuN/PlatformBundle/Entity/Dossier.php
<?php

namespace PHuN\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Dossier
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="PHuN\PlatformBundle\Entity\DossierRepository")
 */
class Dossier
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="PHuN\PlatformBundle\Entity\Catalogue", inversedBy="dossiers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $catalogue;

    /**
     * @ORM\OneToMany(targetEntity="PHuN\PlatformBundle\Entity\Dossier", mappedBy="dossiers")
     */
    private $sousdossier;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Dossier
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set catalogue
     *
     * @param \PHuN\PlatformBundle\Entity\Catalogue $catalogue
     *
     * @return Dossier
     */
    public function setCatalogue(\PHuN\PlatformBundle\Entity\Catalogue $catalogue)
    {
        $this->catalogue = $catalogue;

        return $this;
    }

    /**
     * Get catalogue
     *
     * @return \PHuN\PlatformBundle\Entity\Catalogue
     */
    public function getCatalogue()
    {
        return $this->catalogue;
    }

    /**
     * Get Dossier
     *
     * @return \PHuN\PlatformBundle\Entity\Dossier
     */
    public function getDossier()
    {
        return $this;
    }
}

src/PHuN/PlatformBundle/Form/TranscriptionType.php
<?php

namespace PHuN\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TranscriptionType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content',    'textarea')
            //->add('date',       'date')
            //->add('page',       'integer')
            //->add('user',       'text')
            //->add('published',  'checkbox', array('required' => true))
            ->add('revision', 'checkbox', array('label' => 'Envoyer en relecture','required' => false))
            ->add('save',       'submit', array('label' => 'Sauvegarder'))
            ->add('save_exit',       'submit', array('label' => 'Enregistrer et Fermer'))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PHuN\PlatformBundle\Entity\Transcription'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'phun_platformbundle_transcription';
    }
}

src/PHuN/PlatformBundle/Controller/TranscriptionController.php
<?php

namespace PHuN\PlatformBundle\Controller;

use PHuN\PlatformBundle\Editor\EditorConfig;
use PHuN\PlatformBundle\Form\CorpusType;
use PHuN\PlatformBundle\Form\TranscriptionType;
use PHuN\PlatformBundle\Entity\Image;
use PHuN\PlatformBundle\Entity\Page;
use PHuN\PlatformBundle\Entity\Comment;
use PHuN\PlatformBundle\Form\CommentType;
use PHuN\PlatformBundle\Controller\CommentController;
use PHuN\PlatformBundle\Entity\Corpus;
use PHuN\PlatformBundle\Entity\Plugin;
use PHuN\PlatformBundle\Entity\Transcription;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse; //important use for RedirectResponse
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;


class TranscriptionController extends Controller
{
    /**
     * Opens editor allowing to edit a selected transcription by $id
     * @param integer $id Unique id of the page to be transcribed
     * @param Request $request
     * @return twig containing editor interface and view of a page
     */
    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        // Transcription repository
        $repository = $em->getRepository('PHuNPlatformBundle:Transcription');

        // Recovery of transcription by $id
        $transcription = $repository->find($id);
        $page = $transcription->getPage();
        $corpusId = $page->getCorpus()->getId();

        $this->denyAccessUnlessGranted('ROLE_AUTEUR');
        // Get user
        $user = $this->getUser();

        $url_xml = $transcription->getUrlXml(); 
        if (is_file($url_xml) == null) {
                $contenu_xml = simplexml_load_file("transcriptionMinimal.xml");
        }
        else {
            $contenu_xml = simplexml_load_file($url_xml);
        }        

        $contenu = $contenu_xml->contenu;
        $xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>";

        // Transform and save into a new XML file
        $contenu =  $contenu->asXML();
        $contenu = str_replace("<contenu>", "", $contenu);
        $contenu = str_replace("</contenu>", "", $contenu);

        // The transcription content is set to be seen in the form
        $transcription->setContent( $contenu ); // Ici, remplacement du $content_xml integral par $contenu (fichier sans descriptif)

        // Form creation for the transcription
        $form = $this->get('form.factory')->create(new TranscriptionType(), $transcription);

        // Recover corpus by $id
        $corpus = $this->getDoctrine()->getManager()->getRepository('PHuNPlatformBundle:Corpus')->find($corpusId);

        $containerList = $this->getDoctrine()->getManager()->getRepository('PHuNPlatformBundle:Container')->findAll();    
        // Editor configuration
        $listPlugins = $corpus->getPlugins();
        $stylesheet  = $corpus->getStylesheet()->getUrl();
        $editConfig = new EditorConfig($listPlugins, $stylesheet, $containerList);
        $tiny_conf = $editConfig->createEditorConfig();

        /**
        * Calls CommentController function viewCommentsAction used to recover all comments for page
        */
        $commentController = new CommentController($em);
        $formFactory = $this->get('form.factory');
        $commentArray = $commentController->viewCommentsAction($id, $user, $formFactory, $request);

        // Action when user saves and exits transcription
        if ( $form->handleRequest($request)->isValid() )
        {   
            if ($form->get('save_exit')->isClicked()) {

                return $this->saveAndExit( $page, $user, $transcription, $corpus, $stylesheet, $form );

            }
            // If user saves transcription to continues working 
            else if($form->get('save')->isClicked()) {

                return $this->simpleSave ( $page, $user, $transcription, $corpus, $stylesheet, $form, $tiny_conf, $commentArray );
            }

        }


    /**    END OF FORM CREATION AND HANDLING		**/
    /********************************************************/

    return $this->render('PHuNPlatformBundle:Transcription:edit.html.twig',
        array('page' => $page,
            'corpus' => $corpus,
            'form' => $form->createView(),
            'tiny_conf' => $tiny_conf,
            'listComments' => $commentArray["listComments"],
            'form_comment' => $commentArray['form_comment']->createView(),
            'transcription' => $transcription,
            'stylesheet' => $stylesheet

        ));

    }


    /**
     * Displays view of transcription corresponding to $id
     * @param integer $id
     * @return twig view of selected transcription
     */
    public function viewAction($id)
    {

        $repository = $this->getDoctrine()->getManager()->getRepository('PHuNPlatformBundle:Transcription');

        $transcription = $repository->find($id);
        $page = $transcription->getPage();
        $corpus = $page->getCorpus();
        $stylesheet = $corpus->getStylesheet();
        $urlCSS = $stylesheet->getUrl();

        $listUsers = array();
        $listTranscriptions = $repository->findByPage($page);

        foreach( $listTranscriptions as $tr ) {
            $listUsers[] = $tr->getUser();
        }
        $listUsers = array_unique($listUsers);
        $em = $this->getDoctrine()->getManager();
        $UserRepository = $em->getRepository('PHuNUserBundle:User');
        foreach( $listTranscriptions as $tr ) {
            $rId1 = $tr->getUserRevision1();
            $rId2 = $tr->getUserRevision2();
            $rId3 = $tr->getUserRevision3();

            $r1 = $UserRepository->findOneById($rId1);
            $r2 = $UserRepository->findOneById($rId2);
            $r3 = $UserRepository->findOneById($rId3);
        }

        return $this->render('PHuNPlatformBundle:Transcription:view.html.twig', array(
            'page' => $page,
            'corpus' => $corpus,
            'transcription' => $transcription,
            'urlCSS' => $urlCSS,
            'listUsers' => $listUsers,
            'r1'        => $r1,
            'r2'        => $r2,
            'r3'        => $r3
        ));
    }

    /**
     * Save and exit function. One of two types of save functions
     * @param Page $page
     * @param User $user
     * @param Transcription $transcription
     * @param Corpus $corpus
     * @param Stylesheet $stylesheet
     * @param Form $form
     */
    public function saveAndExit( $page, $user, $transcription, $corpus, $stylesheet, $form ) {
        // Redirect to view the newly saved page
        $pageName       = $page->getFileName();
        $corpusName     = $corpus->getName();
        $corpusId       = $corpus->getId();
        $folder_name    = 'corpus/'.$corpusName.'_'.$corpusId.'/transcriptions/'.$pageName.'/';


        $newTranscription = $transcription;
        $newTranscription->setDate(new \Datetime());
        $newTranscription->setPage( $transcription->getPage() );
        $newTranscription->setUser( $user );
        $newTranscription->setContent( $transcription->getContent() );
        $newTranscription->setUrlXml("NULL");
        $newTranscription->setPublished(false);

        if ($form['revision']->getData() == false) {
            $newTranscription->setNbRevisions(-1);
            $newTranscription->setPublished(false);
        }

        if ($form['revision']->getData() == true) {
            $nbRevisions = $newTranscription->getNbRevisions()+ 1;
            $transcription->setRevision(true);
            $newTranscription->setNbRevisions($nbRevisions); 
            $newTranscription->setPublished(false);


            if ($form['revision']->getData() == true && $newTranscription->getNbRevisions() == 3) {
                $newTranscription->setPublished(true);
                $newTranscription->setRevision(false);
            }
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($newTranscription);
        $em->flush();

        $userName = $user->getUsername();
        $content  = $newTranscription->getContent();
        $id       = $newTranscription->getId();

        $pathx_copyfile = $folder_name . $pageName . '_' . $id . '.xml';
        $newTranscription->setUrlXml($pathx_copyfile);
        $em->persist($newTranscription);
        $em->flush();
        
        
        $xmlHeader = "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
        $debut = "<page><contenu>";
        $fin   = "</contenu></page>";
        $filexml = $xmlHeader.$debut.$content.$fin;

        // Create folder for new file if it doesn't already exist 
        if (!file_exists($folder_name)) {
            mkdir($folder_name, 0755, true);
        }
        // Write file to folder
        file_put_contents($pathx_copyfile, $filexml);

        return $this->redirect($this->generateUrl('phun_platform_transcription_view', array(
                'id' => $id,
                'corpus' => $corpus,
                'transcription' =>$transcription,
                'stylesheet' => $stylesheet
        )));
    }

    /**
     * Simple save function. User does not leave the page with this type of save
     * @param Page $page
     * @param User $user
     * @param Transcription $transcription
     * @param Corpus $corpus
     * @param Stylesheet $stylesheet
     * @param Form $form
     * @param string $tiny_conf
     * @param array $commentArray
     */
    public function simpleSave( $page, $user, $transcription, $corpus, $stylesheet, $form, $tiny_conf, $commentArray ) {
        // Persist transcription
        $newTranscription = $transcription;
        $em = $this->getDoctrine()->getManager();
        $em->persist($newTranscription);

        // Reload saved transcription 
        $form = $this->get('form.factory')->create(new TranscriptionType(), $newTranscription);

src/PHuN/PlatformBundle/Resources/views/Transcription/confirmation.html.twig
{# src/PHuN/PlatformBundle/Resources/views/Page/edit.html.twig #}

{% extends "PHuNPlatformBundle::noMenuLayout.html.twig" %}

{% block title %}
  Transcription d'une page - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('mb-tooltip/css/mbTooltip.css') }}" title="style1"  media="screen">

{% endblock %}

{%block body %}

<h2>{{ page.alt }}</h2>

  <div class="well">
    {{ page.corpus.name }}
  </div>

  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
	{{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
  {{ form_end(form) }}

{% endblock %}

src/PHuN/PlatformBundle/Resources/views/Transcription/edit.html.twig
{# src/PHuN/PlatformBundle/Resources/views/Transcription/edit.html.twig #}

{% extends "PHuNPlatformBundle::layout.html.twig" %}


{% block title %}
  Transcription d'une page - {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/framework/css/page_styles.css') }}" type="text/css" />
{% endblock %}

{% block body %}

    {{ render(controller("PHuNPlatformBundle:Corpus:Header", { 'id': corpus.id } )) }}
    
    {% if page.sousDossier.name is same as("unnamed")  %}
        <h3>
            Catalogue {{ page.sousDossier.dossier.catalogue.name}}, Dossier {{ page.sousDossier.dossier.name }}, Page {{ page.alt }}
        </h3>
    {% else %}
        <h3>
            Catalogue {{ page.sousDossier.dossier.catalogue.name}}, Dossier {{ page.sousDossier.dossier.name }}, Chemise {{ page.sousDossier.name }}, Page {{ page.alt }}
        </h3>
    {% endif %}


  <div class="row">
     <div class="col-md-6">
      {% if page.urlImg is not null %}
        <img src="{{ asset(page.urlImg) }}" id="zoom_05" alt="{{ page.alt }}" height="100%" width="100%" data-zoom-image="{{ asset(page.urlImg) }}" >
    {% endif %} 
    </div>

     <div class="col-md-6">
      <div class="comment">
          <a type="button" class="btn btn-info" id="comment-button">
          <i class="glyphicon glyphicon-comment"></i>
              Commentaires pour cette page</a>
      </div>

            {# The Modal #}
      <div id="comment-modal" class="modal">

         {# Modal content #}
        <div class="modal-content">
            <span class="close">×</span>
            <div class="comment-form">

              {{ form_start(form_comment, {'attr': {'class': 'form-horizontal'}}) }}
              
                <div class="form-group">
                     <div class="col-md-2">
                        <div class="comment-user-profile"> 
                          <img src="{{ asset(app.user.avatar.url)}}" height="30"/>
                        </div> 
                        <div class="comment-user">{{ app.user.username }}</div>
                     </div> 
                     <div class="col-md-8">
                        {{ form_widget(form_comment.text, {'attr': {'class':'form-control', 'placeholder': 'Entrez votre commentaire ici...'}}) }}
                    </div> 
                    <div class="col-md-2">
                      {{ form_widget(form_comment.save, {'attr': {'class': 'btn btn-primary btn-sm'} }) }}
                      
                    </div>
                  
                </div>
              {{ form_end(form_comment) }}

            </div> 
            {% if listComments is null %}
            <div class="comment-box">
              <p>Pas de commentaires pour cette page..</p>
              <a href="{{ path('phun_new_comment', {'id': page.id}) }}">Rajouter un commentaire</a>
            </div>
            
     
            {% elseif listComments is not null %}
            <div class="row">
              {% for comment in listComments %}
                <div class="comment-box">
                    <div class="comment-user-profile"> <img src="{{ asset(comment.user.avatar.url) }}" height="30"/></div>
                    <div class="comment-user">{{ comment.user.username }}</div>
                    <div class="comment-datetime">{{ comment.datetime|date('d/m/Y \\à g:ia') }}</div>
                    <div class="comment-text">{{ comment.text }}</div>
                    <div class="comment-time-ago">{{ comment.datetime|time_ago_in_words(true, true) }}</div>
                </div>      
              
              {% endfor %}
            </div>

            <div class="col-xs-12" style="height:30px;"></div>
            {% endif %}
            
        </div>

      </div>

        {{ form_start(form, {'attr': {'class': 'form-horizontal', 'action': '/post/new', 'method': 'post'}}) }}

          {# Les erreurs générales du formulaire #}
          {{ form_errors(form) }}
          {#  <textarea src="{{ page.urlXml }}" alt="{{ page.alt }}"height="320" width="40%"></textarea> #}
          {# {{ form_rest(form) }} #}

          <div class="form-group">
              {#{{ form_label(form.content, "Transcription", {'label_attr': {'class': 'col-sm-3 control-label'}})}}#}
              <div class="col-md-12">
                  {{ form_widget(form.content, {'attr': {'class':'tinymce','rows':'20', 'data-theme':'advanced', 'encoding': 'xml'}}) }} 
              </div>  
          </div>  

          {#<div class="form-group">
            {{ form_label(form.published, "Published", {'label_attr': {'class': 'col-sm-3 checkbox'}}) }}
            
            {{ form_widget(form.published) }}
                  
          </div>#}


          
          <div class="form-group">
            <div class="col-md-12">
              <div class="input-group">
                  {{ form_widget(form.revision, {'attr': {'class': 'checkbox-inline'}}) }}   
                  {{ form_label(form.revision, "Envoyer en relecture", {'label_attr': {'class': 'col-md-12 control-label-inline'}})}}
              </div>   
            </div>    
          </div> 
          {# Les boutons d'enregistrement #}
          {{ form_widget(form.save, {'attr': {'class': 'btn btn-success'} }) }}
          {{ form_widget(form.save_exit, {'attr': {'class': 'btn btn-primary'} }) }}

          {#<p><a href="{{ path('phun_platform_revision', {'id': page.id}) }}" class="btn btn-default">
          Envoyer en relecture
          </a></p>#}
        {{ form_end(form) }} 
        
       {#{{ transcription.content }}#}

    </div>
  </div>



  {#<p> 
    <a href="{{ path('phun_platform_view', {'id': page.id-1}) }}" class="btn btn-default">
          page précédente
    </a>

    <a href="{{ path('phun_platform_view', {'id': page.id+1}) }}" class="btn btn-default">
          page suivante 
    </a>
  </p>#}


  {{ include(template_from_string(tiny_conf)) }}
  


{#<div id="begin">beg: </div>
<div id="end">end: </div>
<div id="middle">mid: </div>#}

{{ render(controller("PHuNPlatformBundle:Corpus:Footer", { 'id': corpus.id } )) }}

{% endblock %}




{% block javascripts %}
{{ parent() }}
{#<script type="text/javascript" src="{{ asset('mb-tooltip/inc/jquery.timers.js') }}"></script>
<script type = "text/javascript" src = "{{ asset('mb-tooltip/inc/mbTooltip.js')}}"/>#}
<script type = "text/javascript" src = "{{ asset('sisyphus/sisyphus.min.js')}}"/>
<script type = "text/javascript" src = "{{ asset('http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.1.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.6/src/jquery.ez-plus.js') }}"></script>
  <script type="text/javascript">
    $("#zoom_05").ezPlus({
        zoomType: 'inner',
        cursor: 'crosshair',
        lensBorder : 0,
        borderSize : 0.5,
        zoomSize : 200,
        scrollZoom: true,
        easing: false,
        responsive : true
        

      });
  </script>
<script>
  $('form').sisyphus();
</script>

<script>
  // variable declaration
  var modal = document.getElementById('comment-modal'); 
  var btn = document.getElementById("comment-button"); 
  var span = document.getElementsByClassName("close")[0];

  // Onclick button event to open the modal 
  btn.onclick = function() {
      modal.style.display = "block"; 
  }

  // Onclick even to close the modal
  span.onclick = function() {
      modal.style.display = "none";
  }

  // Clicking anywhere outside the modal will close the modal
  window.onclick = function(event) {
      if (event.target == modal) {
          modal.style.display = "none";
      }
  }
</script>
<script>
$(function(){
  $("title").mbTooltip({
    opacity : .90, // opacity
    wait:300, //time in seconds
    ancor:"mouse", //"parent"
    cssClass:"default", // default = default
    timePerWord:70, //time to show in milliseconds per word
    hasArrow:false,
    color:"white",
    imgPath:"images/",
    shadowColor:"black",
    fade:500
  });
})
</script>

<script>
    $( "#select-text" ).mouseenter(function() {
  $( "#select-text" ).append( "<div>Cliquer pour sélectionner l'ensemble du texte</div>" );
});
</script>

{% endblock %}

src/PHuN/PlatformBundle/Resources/views/Transcription/listAll.html.twig
{# src/PHuN/PlatformBundle/Resources/views/Page/view.html.twig #}

{% extends "PHuNPlatformBundle::layout.html.twig" %}


{% block title %}
  Affichage d'une page - {{ parent() }}
{% endblock %}


{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}


  <div class="row">
    <table class="table table-striped">
       <thead>
        <tr>
          {#<th>Date</th>#}
          <th>Page Source</th>
          <th>Page Id</th>
          <th>User</th>
          <th>Date</th>
        </tr>
      </thead>
    {% for transcription in listTranscriptions %}
    <div class="col-md-9">
      <tr>
      <td>
      
        {% if transcription.page.urlImg is not null %}
          <img src="{{ asset(transcription.page.urlImg) }}" id="zoom_04" alt="{{ transcription.page.alt }}" height="65" data-zoom-image="{{ asset(transcription.page.urlImg) }}" >
      {% endif %}
      </td>
      <td>
        {{ transcription.id }}
      </td>
      <td> 
      {% if transcription.user.username is not null %}
        {{ transcription.user.username }} 
      {% endif %} 
      </td>
      <td>
      {% if transcription.date is not null %}
         {{ transcription.date|date('Y-m-d') }}
      {% endif %} 
      </td>
      <td>
      {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
          <a href="{{ path('phun_platform_transcription_view', {'id': transcription.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Voir la transcription
          </a> 
          {% else %}
          <a href="{{ path('fos_user_security_login', {'id': transcription.page.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Login pour voir la transcription
          </a>
          {% endif %}
      </td>
      </tr>
    </div>  
  
 {% endfor %}
  </table> 



  {#<p>
      <div class="row">
        <div class="col-md-4">
          <a href="{{ path('phun_platform_view', {'id': transcription.page.id-1}) }}" class="btn btn-default">
                page précédente
          </a>

          <a href="{{ path('phun_platform_view', {'id': transcription.page.id+1}) }}" class="btn btn-default">
                page suivante 
          </a>
        </div>
        <div class="col-md-4 col-md-offset-2">
          {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
          <a href="{{ path('phun_platform_transcription_edit', {'id': transcription.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Editer la transcription
          </a> 
          {% else %}
          <a href="{{ path('fos_user_security_login', {'id': transcription.page.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Transcrire la page
          </a>
          {% endif %}
        </div>  
        <div class="col-md-4 col-md-offset-3">
          <a href="{{ path('phun_platform_transcription_list', {'id': transcription.page.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Liste des transcriptions pour cette page
          </a> 
        </div>  
        
       </div> 
  </p>#}

{% endblock %}

{% block javascripts %}

{#
  <script>
    var cssLink = document.createElement("link");
    cssLink.setAttribute("href", "{{ urlCSS }}");

    var doc = document.getElementById("frame").contentWindow.document;

    doc.head.appendChild(cssLink);

    //Doc = document.getElementById("frame");
    //Doc.head.appendChild(link);
    doc.body.appendChild({{ transcription.content|raw('html') }});
  </script>
#}



{% endblock %}